(function () {
  'use strict';
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const packageNameRegex=/^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$/;
  const blacklistState=new Map();
  function requireLogin() { const login=document.getElementById('loginScreen'); if(login) login.style.display='flex'; }
  function deviceById(id) { const devices=Array.isArray(window.__allDevices)?window.__allDevices:[]; return devices.find(d=>d&&d.deviceId===id)||null; }
  function blacklistHtml(deviceId,active){return `<div class="full-open-blacklist" data-blacklist="${esc(deviceId)}"><div class="full-open-blacklist-title">רשימה שחורה פרטית</div><div class="full-open-note">${active?'במצב הפתוח כל האפליקציות מותרות חוץ מהחבילות ברשימה הזו. שינוי נשמר למכשיר הזה בלבד ונשלח אליו מיד.':'אפשר להכין את הרשימה מראש. היא נאכפת כשהמכשיר במצב פתוח.'}</div><div class="full-open-blacklist-add"><input type="text" inputmode="url" autocomplete="off" spellcheck="false" placeholder="com.example.app" data-blacklist-input><button type="button" class="toggle-btn" data-blacklist-add>הוסף</button></div><div class="full-open-blacklist-message" data-blacklist-message>טוען רשימה...</div><div class="full-open-blacklist-list" data-blacklist-list></div></div>`;}
  function cardHtml(deviceId, compact) {
    const d=deviceById(deviceId); const active=d&&d.fullOpenMode===true;
    return `<div class="full-open-card${compact?' compact':''}${active?' active':''}" data-full-open-card="${esc(deviceId)}"><div class="full-open-head"><div><strong>פתיחת המכשיר</strong><div class="full-open-status">${active?'המכשיר פתוח — Google Play זמין וכל אפליקציה מותרת חוץ מהרשימה השחורה':'המכשיר במצב מסונן ומוגבל'}</div></div><span class="full-open-badge ${active?'active':''}">${active?'פתוח':'חסום'}</span></div><div class="full-open-note">Device Owner נשאר פעיל גם במצב פתוח. חסימת איפוס/הסרת ניהול נשארת פעילה, ואפשר להחזיר את המכשיר למצב המסונן מרחוק.</div><div class="full-open-actions">${active?'<button type="button" class="toggle-btn full-open-restore" data-full-open-disable>החזר חסימה וסינון</button>':'<button type="button" class="toggle-btn full-open-enable" data-full-open-enable>פתח עם רשימה שחורה</button>'}</div>${blacklistHtml(deviceId,active)}</div>`;
  }
  async function submit(deviceId, enabled, button) {
    const promptText=enabled?'לפתוח את Google Play ולאפשר את כל האפליקציות חוץ מהרשימה השחורה הפרטית של המכשיר? Device Owner וחסימת איפוס יישארו פעילים.':'להחזיר את החסימה, הסינון ורשימת האפליקציות המאושרות למכשיר?';
    if(!confirm(promptText))return;
    button.disabled=true; const old=button.textContent; button.textContent='שומר ושולח למכשיר...';
    try{
      const res=await fetch(`/api/devices/${encodeURIComponent(deviceId)}/full-open`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});
      if(res.status===401){requireLogin();return;}
      const body=await res.json().catch(()=>({})); if(!res.ok){alert(body.error||'שינוי מצב הפתיחה נכשל');return;}
      const devices=Array.isArray(window.__allDevices)?window.__allDevices:[]; const idx=devices.findIndex(d=>d.deviceId===deviceId); if(idx>=0)devices[idx]=body;
      if(typeof window.loadDevices==='function')await window.loadDevices(); else remount();
    }catch(_){alert('שגיאת תקשורת בשינוי מצב הפתיחה');}
    finally{if(button.isConnected){button.disabled=false;button.textContent=old;}}
  }
  function renderBlacklist(card,deviceId){const holder=card.querySelector('[data-blacklist-list]');const message=card.querySelector('[data-blacklist-message]');if(!holder||!message)return;const list=blacklistState.get(deviceId)||[];holder.innerHTML=list.map(pkg=>`<span class="full-open-blacklist-chip"><code>${esc(pkg)}</code><button type="button" aria-label="הסר ${esc(pkg)}" data-blacklist-remove="${esc(pkg)}">×</button></span>`).join('');message.textContent=list.length?`${list.length} אפליקציות חסומות במכשיר הזה`:'הרשימה ריקה — במצב פתוח אין חסימת אפליקציות לפי package';holder.querySelectorAll('[data-blacklist-remove]').forEach(btn=>btn.addEventListener('click',()=>saveBlacklist(card,deviceId,(blacklistState.get(deviceId)||[]).filter(pkg=>pkg!==btn.getAttribute('data-blacklist-remove')))));}
  async function loadBlacklist(card,deviceId){const message=card.querySelector('[data-blacklist-message]');try{const res=await fetch(`/api/devices/${encodeURIComponent(deviceId)}/blocked-apps`);if(res.status===401){requireLogin();return;}const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'טעינת הרשימה נכשלה');blacklistState.set(deviceId,Array.isArray(body.blockedApps)?body.blockedApps:[]);renderBlacklist(card,deviceId);}catch(error){if(message)message.textContent=error.message||'טעינת הרשימה נכשלה';}}
  async function saveBlacklist(card,deviceId,list){const message=card.querySelector('[data-blacklist-message]');const add=card.querySelector('[data-blacklist-add]');if(add)add.disabled=true;if(message)message.textContent='שומר ושולח למכשיר...';try{const res=await fetch(`/api/devices/${encodeURIComponent(deviceId)}/policy/blocked-apps`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({blockedApps:list})});if(res.status===401){requireLogin();return;}const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'שמירת הרשימה נכשלה');blacklistState.set(deviceId,Array.isArray(body.blockedApps)?body.blockedApps:[]);renderBlacklist(card,deviceId);}catch(error){if(message)message.textContent=error.message||'שמירת הרשימה נכשלה';}finally{if(add&&add.isConnected)add.disabled=false;}}
  function bind(card){if(!card||card.dataset.bound==='1')return;card.dataset.bound='1';const id=card.getAttribute('data-full-open-card');card.querySelector('[data-full-open-enable]')?.addEventListener('click',e=>submit(id,true,e.currentTarget));card.querySelector('[data-full-open-disable]')?.addEventListener('click',e=>submit(id,false,e.currentTarget));const input=card.querySelector('[data-blacklist-input]');const add=card.querySelector('[data-blacklist-add]');const addPackage=()=>{const pkg=(input?.value||'').trim();if(!packageNameRegex.test(pkg)){const message=card.querySelector('[data-blacklist-message]');if(message)message.textContent='יש להזין package name תקין, לדוגמה com.example.app';return;}const next=[...new Set([...(blacklistState.get(id)||[]),pkg])].sort();if(input)input.value='';saveBlacklist(card,id,next);};add?.addEventListener('click',addPackage);input?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();addPackage();}});loadBlacklist(card,id);}
  function mountUnified(){const panel=document.getElementById('unifiedCustomerProfile');if(!panel||panel.style.display==='none'||panel.querySelector('[data-full-open-card]'))return;const manage=panel.querySelector('.unified-profile-actions');const button=panel.querySelector('[data-unified-manage]');const id=button&&button.getAttribute('data-unified-manage');if(!id)return;const holder=document.createElement('div');holder.innerHTML=cardHtml(id,true);const card=holder.firstElementChild;manage?manage.insertAdjacentElement('beforebegin',card):panel.appendChild(card);bind(card);}
  function mountDetail(){const detail=document.getElementById('detailContent');if(!detail||!detail.children.length||detail.querySelector('[data-full-open-card]'))return;const id=window.__currentDetailDeviceId||null;if(!id)return;const holder=document.createElement('div');holder.innerHTML=`<div class="detail-section"><h3>פתיחת המכשיר</h3>${cardHtml(id,false)}</div>`;const section=holder.firstElementChild;const exception=[...detail.querySelectorAll('.detail-section')].find(s=>s.querySelector('h3')?.textContent.trim()==='החרגת מנוי');const subscription=[...detail.querySelectorAll('.detail-section')].find(s=>s.querySelector('h3')?.textContent.trim()==='מנוי');const anchor=exception||subscription;anchor?anchor.insertAdjacentElement('afterend',section):detail.appendChild(section);bind(section.querySelector('[data-full-open-card]'));}
  function remount(){mountUnified();mountDetail();}
  new MutationObserver(remount).observe(document.body,{childList:true,subtree:true}); document.addEventListener('DOMContentLoaded',remount); setTimeout(remount,0);
})();
